language: objective-c
sudo: false

matrix:
  include:
    # tests with Xcode 9.x & Xcode 10.1, the rest with 10.2
    - osx_image: xcode9.3
      env: TRAVIS_NODE_VERSION=10
    - osx_image: xcode10.1
      env: TRAVIS_NODE_VERSION=10
    # others with Xcode 10.2
    - osx_image: xcode10.2
      env: TRAVIS_NODE_VERSION=6
    - osx_image: xcode10.2
      env: TRAVIS_NODE_VERSION=8
    - osx_image: xcode10.2
      env: TRAVIS_NODE_VERSION=10
    - osx_image: xcode10.2
      env: TRAVIS_NODE_VERSION=12
    # with an extra with Xcode 10.1
    - osx_image: xcode10.1
      env: TRAVIS_NODE_VERSION=12

before_install:
  - nvm install $TRAVIS_NODE_VERSION

install:
  - npm install
  - npm install ios-deploy
  - npm install -g codecov

script:
  - node --version
  - npm --version
  - npm run eslint
  - npm run unit-tests
  - npm run test:component
  - npm run e2e-tests
  - npm run objc-tests
  - npm run cover

after_script:
  - codecov
